import cv2 # OpenCV library for image processing
import face_recognition # face_recognition library for face detection and recognition
import numpy as np # NumPy library for numerical operations (not used in this basic example but can be useful for further processing)
import os # os library for file system operations
from flask import Flask, request, render_template, redirect, url_for, jsonify # Flask library for creating the web application and handling HTTP requests and responses
import base64 # base64 library for encoding and decoding image data in base64 format (used for handling images captured from the camera in the frontend)
from io import BytesIO # BytesIO library for handling in-memory byte streams (used for processing images captured from the camera without saving them to disk)
from PIL import Image # PIL (Pillow) library for image processing (used for handling images captured from the camera in the frontend)
import logging # logging library for logging messages and errors in the application

# Initialize logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s') # Set up logging configuration to log messages with timestamp, log level, and message content. This will help in debugging and monitoring the application.

app = Flask(__name__) # Create a Flask application instance to handle web requests and responses for the face recognition system. This will allow us to create routes for uploading images, capturing images from the camera, and processing them for face detection and recognition.

# Ensure the 'uploads/' directory exists
UPLOAD_FOLDER = 'uploads' # Define the folder where uploaded images will be stored. This is important for organizing the files and ensuring that the application has a designated location to save and access uploaded images for processing.
os.makedirs(UPLOAD_FOLDER, exist_ok=True) # Create the 'uploads/' directory if it doesn't already exist. This ensures that the application can save uploaded images without encountering errors due to a missing directory. The 'exist_ok=True' parameter allows the function to succeed even if the directory already exists, preventing unnecessary errors.
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER # Set the upload folder configuration for the Flask application. This allows us to easily reference the upload folder path throughout the application when saving and accessing uploaded images. By centralizing this configuration, we can maintain cleaner code and make it easier to update the upload folder path in the future if needed. 

# Set the device index for DroidCam (replace 1 with the correct index for your setup)
droidcam_index = 1

# List all available camera indices
def list_camera_indices(): # Function to list all available camera indices on the system. This is useful for identifying which index corresponds to the DroidCam or any other connected cameras, allowing us to set the correct index for capturing video from the desired camera.
    index = 0 # Start with the first camera index (0) and increment until no more cameras are found. This loop will attempt to open each camera index and check if it can read a frame, indicating that a camera is available at that index. If a camera is found, it will print the index; otherwise, it will print a message indicating that no camera was found at that index and break the loop.
    while True: # Loop indefinitely to check for available camera indices until no more cameras are found
        cap = cv2.VideoCapture(index) # Attempt to open the camera at the current index using OpenCV's VideoCapture function. This will allow us to check if a camera is available at that index by trying to read a frame from it.
        if not cap.read()[0]:# Check if the camera at the current index can read a frame. If it cannot, it means that there is no camera available at that index, and we will print a message indicating that no camera was found and break the loop to stop checking further indices.
            print(f"Không tìm thấy camera tại index {index}") # Print a message indicating that no camera was found at the current index. This helps in identifying which indices do not have cameras connected, allowing us to focus on the indices that do have cameras for our face recognition system.
            break # Break the loop if no camera is found at the current index, as there is no need to check further indices if we have already reached an index without a camera. This helps in optimizing the process of identifying available cameras on the system.
        else: # If a camera is found at the current index, print a message indicating that a camera was found at that index. This helps in identifying which indices correspond to available cameras, allowing us to set the correct index for capturing video from the desired camera (e.g., DroidCam).
            print(f"Camera found at index {index}") # Print a message indicating that a camera was found at the current index. This helps in identifying which indices correspond to available cameras, allowing us to set the correct index for capturing video from the desired camera (e.g., DroidCam).
        cap.release() # Release the camera resource after checking it to free up system resources and avoid potential conflicts with other applications that may want to access the camera. This is important for maintaining the stability and performance of the application, especially when checking multiple camera indices in a loop.
        index += 1 # Increment the index to check the next camera index in the next iteration of the loop. This allows us to systematically check all available camera indices on the system until we find the desired camera (e.g., DroidCam) or exhaust all indices without finding a camera.

# Uncomment the following line to list camera indices
list_camera_indices() # Call the function to list all available camera indices on the system. This will help us identify which index corresponds to the DroidCam or any other connected cameras, allowing us to set the correct index for capturing video from the desired camera in our face recognition system.

def load_and_detect_face(image_path): # Load an image from the specified path and detect faces in it using the face_recognition library. This function will handle the process of loading the image, converting it to the appropriate color space, and using the face_recognition library to detect faces with improved accuracy by trying both the CNN and HOG models. The results will be logged for better visibility and debugging purposes.
    """Load image and detect faces with improved accuracy""" # Load the image from the specified path and detect faces in it using the face_recognition library. This function will handle the process of loading the image, converting it to the appropriate color space, and using the face_recognition library to detect faces with improved accuracy by trying both the CNN and HOG models. The results will be logged for better visibility and debugging purposes.
    # Load the image
    image = cv2.imread(image_path) # Load the image from the specified path using OpenCV's imread function. This will allow us to read the image file and store it in a format that can be processed for face detection. If the image cannot be loaded (e.g., due to an incorrect path or unsupported format), we will log an error message and return None for the image and an empty list for face locations to indicate that the loading process failed.
    if image is None: # Check if the image was loaded successfully. If the image is None, it means that the loading process failed (e.g., due to an incorrect path or unsupported format), and we will log an error message and return None for the image and an empty list for face locations to indicate that the loading process failed.
        print(f" Failed to load image: {image_path}") # Print an error message indicating that the image failed to load. This helps in identifying issues with the image path or format, allowing us to troubleshoot and fix the problem for successful face detection.
        logging.error(f"Failed to load image: {image_path}") # Log an error message indicating that the image failed to load. This helps in identifying issues with the image path or format, allowing us to troubleshoot and fix the problem for successful face detection. Logging the error also provides a record of the issue for future reference and debugging purposes.
        return None, [] #       Return None for the image and an empty list for face locations to indicate that the loading process failed. This allows the calling function to handle the failure case appropriately (e.g., by displaying an error message to the user or skipping further processing for this image) without causing the application to crash or behave unexpectedly due to a missing or invalid image.

    # Convert image to RGB color space
    rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # Convert the image from BGR color space (used by OpenCV) to RGB color space (used by face_recognition) for accurate face detection. This is necessary because the face_recognition library expects images in RGB format, and using the correct color space ensures that the face detection algorithm can accurately identify faces in the image. If we were to use the BGR color space directly, it could lead to incorrect face detection results due to the mismatch in color representation between OpenCV and face_recognition.
    
    # Detect face locations with CNN model for better accuracy
    try: # Try to use the CNN model for face detection, which generally provides higher accuracy compared to the HOG model, especially in challenging conditions (e.g., low light, occlusions). However, the CNN model requires more computational resources, so we will attempt to use it first and fall back to the HOG model if the CNN model is not available or if there is an error during detection. This approach allows us to achieve better accuracy when possible while maintaining compatibility with systems that may not support the CNN model.
        # Try using CNN model for higher accuracy (requires more computation)
        face_locations = face_recognition.face_locations(rgb_image, model='cnn') # Attempt to detect face locations in the RGB image using the CNN model provided by the face_recognition library. This model is generally more accurate than the HOG model, especially in challenging conditions (e.g., low light, occlusions), but it requires more computational resources. If the CNN model is not available or if there is an error during detection, we will catch the exception and fall back to using the HOG model for face detection.
        print(f" Face detection model: CNN (high accuracy)") # Print a message indicating that the CNN model is being used for face detection, which provides higher accuracy. This helps in understanding which model is being used for face detection and can be useful for debugging and performance monitoring purposes, especially when comparing the results of different models or when troubleshooting issues related to face detection accuracy.
    except: # If there is an error during face detection with the CNN model (e.g., due to lack of support for the model on the system or other issues), we will catch the exception and fall back to using the HOG model for face detection. The HOG model is a more traditional method for face detection that is less computationally intensive but may not perform as well in challenging conditions compared to the CNN model. This fallback mechanism ensures that we can still perform face detection even if the CNN model is not available, albeit with potentially lower accuracy.
        # Fall back to HOG model if CNN is not available
        face_locations = face_recognition.face_locations(rgb_image, model='hog') # If there is an error during face detection with the CNN model, we will fall back to using the HOG model for face detection. The HOG model is a more traditional method for face detection that is less computationally intensive but may not perform as well in challenging conditions compared to the CNN model. This fallback mechanism ensures that we can still perform face detection even if the CNN model is not available, albeit with potentially lower accuracy.
        print(f" Face detection model: HOG (standard)") # Print a message indicating that the HOG model is being used for face detection, which is the standard method. This helps in understanding which model is being used for face detection and can be useful for debugging and performance monitoring purposes, especially when comparing the results of different models or when troubleshooting issues related to face detection accuracy. It also provides insight into the computational resources being used for face detection, as the HOG model is less resource-intensive than the CNN model.
    
    # Log results
    num_faces = len(face_locations) # Get the number of faces detected by counting the length of the face_locations list. This allows us to log and display the number of faces found in the image, which can be useful for monitoring the performance of the face detection process and for providing feedback to the user about the results of the detection.
    if num_faces > 0: #         Check if any faces were detected (i.e., if the number of faces is greater than 0). If faces were detected, we will log the number of faces found and their positions in the image. This information can be useful for debugging, performance monitoring, and providing feedback to the user about the results of the face detection process. If no faces were detected, we will log a warning message indicating that no faces were found in the image.
        print(f" Found {num_faces} face(s) in image: {image_path}") # Print a message indicating the number of faces found in the image along with the image path. This provides feedback to the user about the results of the face detection process and can be useful for monitoring the performance of the detection algorithm, especially when processing multiple images or when troubleshooting issues related to face detection accuracy.
        logging.info(f"Found {num_faces} face(s) in image: {image_path}")#      Log an informational message indicating the number of faces found in the image along with the image path. This provides feedback to the user about the results of the face detection process and can be useful for monitoring the performance of the detection algorithm, especially when processing multiple images or when troubleshooting issues related to face detection accuracy. Logging this information also creates a record of the detection results for future reference and analysis.
        for i, (top, right, bottom, left) in enumerate(face_locations): # Loop through each detected face location and print its position in the image. The face_locations list contains tuples of (top, right, bottom, left) coordinates for each detected face, and we will enumerate through this list to provide a numbered output for each face found in the image. This information can be useful for debugging, performance monitoring, and providing feedback to the user about the specific locations of detected faces in the image.
            print(f"   Face {i+1}: Position (top={top}, right={right}, bottom={bottom}, left={left})") # Print the position of each detected face in the image, including the top, right, bottom, and left coordinates. This provides detailed feedback to the user about the specific locations of detected faces in the image, which can be useful for debugging, performance monitoring, and further processing (e.g., drawing boxes around detected faces or cropping them for recognition). The enumeration allows us to number each detected face for easier reference in the output.
    else: # If no faces were detected (i.e., if the number of faces is 0), we will log a warning message indicating that no faces were found in the image. This provides feedback to the user about the results of the face detection process and can be useful for troubleshooting issues related to face detection accuracy, especially when processing multiple images or when testing the application with different types of images (e.g., images with varying lighting conditions, angles, or occlusions).
        print(f" No faces found in image: {image_path}") # Print a message indicating that no faces were found in the image along with the image path. This provides feedback to the user about the results of the face detection process and can be useful for troubleshooting issues related to face detection accuracy, especially when processing multiple images or when testing the application with different types of images (e.g., images with varying lighting conditions, angles, or occlusions).
        logging.warning(f"No faces found in image: {image_path}") # Log a warning message indicating that no faces were found in the image along with the image path. This provides feedback to the user about the results of the face detection process and can be useful for troubleshooting issues related to face detection accuracy, especially when processing multiple images or when testing the application with different types of images (e.g., images with varying lighting conditions, angles, or occlusions). Logging this information also creates a record of the detection results for future reference and analysis, especially when investigating cases where face detection may have failed or produced unexpected results.
    
    return image, face_locations # Return the loaded image and the list of detected face locations. The calling function can use this information to further process the image (e.g., by drawing boxes around detected faces or cropping them for recognition) and to provide feedback to the user about the results of the face detection process. If the loading process failed, the image will be None and the face_locations will be an empty list, allowing the calling function to handle this case appropriately (e.g., by displaying an error message to the user or skipping further processing for this image).

def draw_face_boxes(image, face_locations): # Draw boxes around detected faces
    for top, right, bottom, left in face_locations: # Loop through each detected face location and draw a rectangle around it
        cv2.rectangle(image, (left, top), (right, bottom), (0, 255, 0), 2) # Draw a green rectangle around the detected face with a thickness of 2
    return image # end

def encode_face(image_path): # Encode face from image
    """Mã hóa đặc trưng khuôn mặt từ ảnh.""" # Load the image and convert it to RGB color space for accurate face encoding
    image = cv2.imread(image_path) # Load the image from the specified path
    rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # Convert the image from BGR color space (used by OpenCV) to RGB color space (used by face_recognition) for accurate face encoding.
    encodings = face_recognition.face_encodings(rgb_image) # Mã hóa khuôn mặt trong ảnh và trả về một danh sách các mã hóa (mỗi mã hóa tương ứng với một khuôn mặt được phát hiện)
    return encodings[0] if encodings else None # Return the first encoding if at least one face is detected, otherwise return None

def compare_faces(reference_encoding, folder_path): # Compare the reference face encoding with images in the folder
    """So sánh khuôn mặt tham chiếu với các ảnh trong thư mục.""" # Initialize a dictionary to store the results of face comparison for each image in the folder
    results = {} # Dictionary to store the results of face comparison for each image in the folder
    for file_name in os.listdir(folder_path): # Loop through each file in the specified folder to compare with the reference face encoding
        file_path = os.path.join(folder_path, file_name) # Get the full file path by joining the folder path and the file name
        if not file_name.lower().endswith(('png', 'jpg', 'jpeg')): # Check if the file is an image (with extensions .png, .jpg, or .jpeg) and skip it if it's not an image file
            continue # Skip non-image files in the folder and continue to the next file in the loop

        # Mã hóa khuôn mặt từ ảnh
        encoding = encode_face(file_path) # Encode the face from the current image file to get its encoding for comparison with the reference encoding
        if encoding is None: # Check if the encoding is None, which means no face was detected in the current image, and store a message in the results dictionary if that's the case
            results[file_name] = "Không tìm thấy khuôn mặt" # Store a message in the results dictionary indicating that no face was detected in the current image
            continue # Skip to the next file in the loop if no face is detected in the current image

        # So sánh với khuôn mặt tham chiếu
        match = face_recognition.compare_faces([reference_encoding], encoding)[0] # Compare the current face encoding with the reference encoding and get the result (True if it matches, False otherwise) for the first (and only) comparison since we are comparing with a single reference encoding
        results[file_name] = "Giống" if match else "Khác" # Store the result in the results dictionary indicating whether the current image matches the reference face ("Giống") or not ("Khác")
    return results # Return the results dictionary containing the comparison results for each image in the folder

@app.route('/')  # Define the route for the home page of the web application, which will render the index.html template when accessed. This allows users to access the main interface of the face recognition system where they can upload images or capture images from the camera for processing.
def index(): # Define the function to handle requests to the home page route ('/'). This function will render the index.html template, which serves as the main interface for the face recognition system. Users can interact with this page to upload images or capture images from the camera for processing. By defining this route and function, we enable users to access the web application and utilize its features for face recognition.
    return render_template('index.html') # Render the index.html template when the home page route ('/') is accessed. This allows users to access the main interface of the face recognition system where they can upload images or capture images from the camera for processing. The index.html template should contain the necessary HTML, CSS, and JavaScript to provide a user-friendly interface for interacting with the face recognition features of the application.

@app.route('/upload', methods=['POST']) # Define the route for handling image uploads from the user. This route will accept POST requests, which are typically used for submitting data (in this case, an image file) to the server for processing. By defining this route, we enable users to upload images through the web interface, which can then be processed for face detection and recognition by the application.
def upload_image(): # Define the function to handle POST requests to the '/upload' route for processing uploaded images. This function will check for the presence of an image file in the request, save it to the designated upload folder, and then process it for face detection. The results of the face detection will be returned as a JSON response. By implementing this function, we allow users to upload images through the web interface and receive feedback on the face detection results, enhancing the interactivity and functionality of the face recognition system.
    try: # Wrap the image upload and processing logic in a try-except block to handle any potential errors that may occur during the process. This allows us to catch exceptions, log error messages, and return appropriate error responses to the user without crashing the application. By implementing error handling, we can improve the robustness and user experience of the face recognition system, ensuring that it can gracefully handle issues such as missing files, invalid image formats, or other unexpected errors that may arise during image upload and processing.
        if 'image' not in request.files: # Check if the 'image' key is present in the uploaded files in the request. If it is not present, it means that the user did not upload an image file, and we will log an error message and return a JSON response indicating that no image part was found in the request, along with a 400 Bad Request status code. This helps in providing feedback to the user about the issue with their upload and allows them to correct it by ensuring they include an image file in their request.
            logging.error(" No image part in the request.") # Log an error message indicating that no image part was found in the request. This helps in identifying issues with the user's upload and provides feedback for troubleshooting. Logging this error also creates a record of the issue for future reference and analysis, especially when investigating cases where users may have trouble uploading images or when testing the application with different types of requests.
            print(" No image part in the request.") # Print an error message indicating that no image part was found in the request. This provides immediate feedback to the user about the issue with their upload and allows them to correct it by ensuring they include an image file in their request. This message will be displayed in the console or terminal where the application is running, helping developers and users understand what went wrong during the upload process.
            return jsonify({"error": "No image part in the request."}), 400 # Return a JSON response indicating that no image part was found in the request, along with a 400 Bad Request status code. This informs the user about the issue with their upload and allows them to correct it by ensuring they include an image file in their request. The JSON response provides a structured format for conveying error information, which can be easily parsed and displayed in the frontend of the application for better user experience.

        file = request.files['image'] # Get the uploaded image file from the request using the 'image' key. This allows us to access the file object that contains the uploaded image, which we can then save to the designated upload folder and process for face detection. By retrieving the file from the request, we enable the application to handle user uploads and perform the necessary operations on the uploaded images for face recognition.
        if file.filename == '': # Check if the filename of the uploaded file is empty. If it is empty, it means that the user did not select a file to upload, and we will log an error message and return a JSON response indicating that no file was selected for upload, along with a 400 Bad Request status code. This helps in providing feedback to the user about the issue with their upload and allows them to correct it by ensuring they select a file before attempting to upload.
            logging.error(" No selected file.") # Log an error message indicating that no file was selected for upload. This helps in identifying issues with the user's upload and provides feedback for troubleshooting. Logging this error also creates a record of the issue for future reference and analysis, especially when investigating cases where users may have trouble uploading images or when testing the application with different types of requests.
            print(" No selected file.") # Print an error message indicating that no file was selected for upload. This provides immediate feedback to the user about the issue with their upload and allows them to correct it by ensuring they select a file before attempting to upload. This message will be displayed in the console or terminal where the application is running, helping developers and users understand what went wrong during the upload process.
            return jsonify({"error": "No selected file."}), 400 # Return a JSON response indicating that no file was selected for upload, along with a 400 Bad Request status code. This informs the user about the issue with their upload and allows them to correct it by ensuring they select a file before attempting to upload. The JSON response provides a structured format for conveying error information, which can be easily parsed and displayed in the frontend of the application for better user experience.

        file_path = os.path.join(app.config['UPLOAD_FOLDER'], file.filename) # Create the full file path by joining the upload folder path from the application configuration with the filename of the uploaded file. This allows us to determine where to save the uploaded image on the server, ensuring that it is stored in the designated upload folder for further processing (e.g., face detection). By constructing the file path in this way, we can maintain an organized file structure and easily access the uploaded images when needed for processing.
        file.save(file_path) # Save the uploaded file to the specified file path on the server. This allows us to store the uploaded image in the designated upload folder, making it available for further processing (e.g., face detection). By saving the file, we can ensure that it is accessible for subsequent operations and can be used to provide feedback to the user about the results of the face detection process. Additionally, saving the file creates a record of the uploaded image on the server, which can be useful for logging, debugging, and future reference.
        
        print(f"\n{'='*50}") # Print a separator line for better visibility in the console output, making it easier to distinguish between different upload events and their corresponding logs. This helps in organizing the console output and improving readability, especially when processing multiple uploads or when troubleshooting issues related to image uploads and face detection.
        print(f" Image uploaded: {file.filename}") # Print a message indicating that an image has been uploaded, along with the filename of the uploaded image. This provides immediate feedback in the console about the upload event and helps in tracking which images are being processed by the application. This message will be displayed in the console or terminal where the application is running, helping developers and users understand when an image has been successfully uploaded for processing.
        print(f"{'='*50}") # Print another separator line for better visibility in the console output, making it easier to distinguish between different upload events and their corresponding logs. This helps in organizing the console output and improving readability, especially when processing multiple uploads or when troubleshooting issues related to image uploads and face detection.
        logging.info(f"Image uploaded successfully: {file_path}") # Log an informational message indicating that the image has been uploaded successfully, along with the file path where the image is stored on the server. This provides a record of successful uploads in the application logs, which can be useful for monitoring the application's usage, troubleshooting issues related to uploads, and analyzing patterns in user interactions with the face recognition system. Logging this information also helps in maintaining a history of uploaded images for future reference and analysis.

        # Process the image (e.g., face detection)
        image, face_locations = load_and_detect_face(file_path) # Load the uploaded image and detect faces in it using the load_and_detect_face function. This function will handle the process of loading the image, converting it to the appropriate color space, and using the face_recognition library to detect faces with improved accuracy by trying both the CNN and HOG models. The results will be logged for better visibility and debugging purposes. By processing the image in this way, we can provide feedback to the user about the results of face detection and further utilize this information for face recognition or other features in the application.
        if image is not None: # Check if the image was loaded successfully (i.e., if it is not None) before attempting to draw face boxes. If the image is None, it means that there was an issue with loading the image (e.g., due to an incorrect path or unsupported format), and we will skip the step of drawing face boxes to avoid errors. This check ensures that we only attempt to draw face boxes on valid images, improving the robustness of the application and preventing potential crashes or unexpected behavior when processing invalid images.
            draw_face_boxes(image, face_locations) # If the image was loaded successfully, draw boxes around the detected faces using the draw_face_boxes function. This function will loop through each detected face location and draw a rectangle around it in the image. By drawing face boxes, we can visually indicate where faces were detected in the image, providing feedback to the user about the results of the face detection process. This can enhance the user experience by allowing them to see which faces were identified in their uploaded image and can also be useful for debugging and performance monitoring purposes when testing the application with different types of images.
        
        print(f"{'='*50}\n") # Print a separator line for better visibility in the console output, making it easier to distinguish between different upload events and their corresponding logs. This helps in organizing the console output and improving readability, especially when processing multiple uploads or when troubleshooting issues related to image uploads and face detection.
        return jsonify({"message": "Image processed successfully.", "results": face_locations}) # Return a JSON response indicating that the image was processed successfully, along with the results of face detection (i.e., the locations of detected faces). This provides feedback to the user about the outcome of their upload and allows them to see the results of the face detection process in a structured format. The JSON response can be easily parsed and displayed in the frontend of the application, enhancing the user experience by providing clear and informative feedback about their uploaded image and the detected faces within it.
    except Exception as e: # Catch any exceptions that occur during the image upload and processing steps, log the error message, and return a JSON response indicating that an error occurred along with the error message. This allows us to handle unexpected issues gracefully without crashing the application, providing feedback to the user about what went wrong and allowing them to take corrective action if necessary. By implementing error handling, we can improve the robustness and user experience of the face recognition system, ensuring that it can gracefully handle issues such as missing files, invalid image formats, or other unexpected errors that may arise during image upload and processing.
        print(f" Error processing uploaded image: {str(e)}") # Print an error message indicating that there was an issue processing the uploaded image, along with the specific error message. This provides immediate feedback in the console about the error that occurred during the upload and processing steps, helping developers and users understand what went wrong and allowing them to take corrective action if necessary. This message will be displayed in the console or terminal where the application is running, aiding in troubleshooting and debugging efforts related to image uploads and face detection.
        logging.exception("Error processing the uploaded image.") # Log the exception with a message indicating that there was an error processing the uploaded image. This will include the stack trace and error details in the application logs, which can be useful for troubleshooting and debugging issues related to image uploads and face detection. Logging the exception also creates a record of the error for future reference and analysis, especially when investigating cases where users may have trouble uploading images or when testing the application with different types of requests.
        return jsonify({"error": str(e)}), 500 # Return a JSON response indicating that an error occurred during the processing of the uploaded image, along with the specific error message, and a 500 Internal Server Error status code. This informs the user about the issue that occurred and allows them to take corrective action if necessary. The JSON response provides a structured format for conveying error information, which can be easily parsed and displayed in the frontend of the application for better user experience.

@app.route('/capture', methods=['POST']) # Define the route for handling image capture from the camera. This route will accept POST requests, which are typically used for submitting data (in this case, an image captured from the camera) to the server for processing. By defining this route, we enable users to capture images through the web interface and have them processed for face detection and recognition by the application.
def capture_image(): # Define the function to handle POST requests to the '/capture' route for processing images captured from the camera. This function will check for the presence of image data in the request, decode it from base64 format, save it to the designated upload folder, and then process it for face detection. The results of the face detection will be returned as a JSON response. By implementing this function, we allow users to capture images through the web interface and receive feedback on the face detection results, enhancing the interactivity and functionality of the face recognition system.
    try: #  Wrap the image capture and processing logic in a try-except block to handle any potential errors that may occur during the process. This allows us to catch exceptions, log error messages, and return appropriate error responses to the user without crashing the application. By implementing error handling, we can improve the robustness and user experience of the face recognition system, ensuring that it can gracefully handle issues such as missing image data, invalid image formats, or other unexpected errors that may arise during image capture and processing.
        data = request.get_json() #         Get the JSON data from the request, which should contain the image data captured from the camera in base64 format. This allows us to access the image data that was sent from the frontend when the user captures an image using their camera. By retrieving the JSON data, we can then decode the image and process it for face detection, providing feedback to the user about the results of the detection process.
        if not data or 'image' not in data: # Check if the data is None or if the 'image' key is not present in the data. If either of these conditions is true, it means that there is no image data in the request, and we will log an error message and return a JSON response indicating that no image data was found in the request, along with a 400 Bad Request status code. This helps in providing feedback to the user about the issue with their capture and allows them to correct it by ensuring they include image data in their request when capturing an image from the camera.
            logging.error(" No image data in the request.") # Log an error message indicating that no image data was found in the request. This helps in identifying issues with the user's capture and provides feedback for troubleshooting. Logging this error also creates a record of the issue for future reference and analysis, especially when investigating cases where users may have trouble capturing images or when testing the application with different types of requests.
            print(" No image data in the request.") # Print an error message indicating that no image data was found in the request. This provides immediate feedback to the user about the issue with their capture and allows them to correct it by ensuring they include image data in their request when capturing an image from the camera. This message will be displayed in the console or terminal where the application is running, helping developers and users understand what went wrong during the capture process.
            return jsonify({"error": "No image data in the request."}), 400 # Return a JSON response indicating that no image data was found in the request, along with a 400 Bad Request status code. This informs the user about the issue with their capture and allows them to correct it by ensuring they include image data in their request when capturing an image from the camera. The JSON response provides a structured format for conveying error information, which can be easily parsed and displayed in the frontend of the application for better user experience.

        image_data = data['image'].split(',')[1] # Get the image data from the 'image' key in the data, which is expected to be in base64 format. The image data is typically sent as a data URL (e.g., "data:image/jpeg;base64,..."), so we split the string by the comma and take the second part (index 1) to get the actual base64-encoded image data. This allows us to decode the image data and save it for further processing (e.g., face detection). By extracting the base64 image data, we can handle the captured image appropriately and provide feedback to the user about the results of the face detection process.
        image = Image.open(BytesIO(base64.b64decode(image_data))) # Decode the base64 image data and open it as an image using the PIL library. This allows us to convert the base64-encoded image data into a format that can be processed for face detection. By decoding the image data and opening it as an image object, we can then save it to the designated upload folder and perform face detection on it, providing feedback to the user about the results of the detection process.
        file_path = os.path.join(app.config['UPLOAD_FOLDER'], 'captured_image.jpg') # Create the full file path for saving the captured image by joining the upload folder path from the application configuration with a filename (e.g., 'captured_image.jpg'). This allows us to determine where to save the captured image on the server, ensuring that it is stored in the designated upload folder for further processing (e.g., face detection). By constructing the file path in this way, we can maintain an organized file structure and easily access the captured images when needed for processing.
        image.save(file_path) # Save the captured image to the specified file path on the server. This allows us to store the captured image in the designated upload folder, making it available for further processing (e.g., face detection). By saving the file, we can ensure that it is accessible for subsequent operations and can be used to provide feedback to the user about the results of the face detection process. Additionally, saving the file creates a record of the captured image on the server, which can be useful for logging, debugging, and future reference.
        
        print(f"\n{'='*50}") # Print a separator line for better visibility in the console output, making it easier to distinguish between different capture events and their corresponding logs. This helps in organizing the console output and improving readability, especially when processing multiple captures or when troubleshooting issues related to image capture and face detection.
        print(f" Image captured from camera") # Print a message indicating that an image has been captured from the camera. This provides immediate feedback in the console about the capture event and helps in tracking which images are being processed by the application. This message will be displayed in the console or terminal where the application is running, helping developers and users understand when an image has been successfully captured for processing.
        print(f"{'='*50}") # Print another separator line for better visibility in the console output, making it easier to distinguish between different capture events and their corresponding logs. This helps in organizing the console output and improving readability, especially when processing multiple captures or when troubleshooting issues related to image capture and face detection.
        logging.info(f"Image captured and saved successfully: {file_path}") # Log an informational message indicating that the image has been captured and saved successfully, along with the file path where the image is stored on the server. This provides a record of successful captures in the application logs, which can be useful for monitoring the application's usage, troubleshooting issues related to captures, and analyzing patterns in user interactions with the face recognition system. Logging this information also helps in maintaining a history of captured images for future reference and analysis.

        # Process the image (e.g., face detection)
        image, face_locations = load_and_detect_face(file_path) # Load the captured image and detect faces in it using the load_and_detect_face function. This function will handle the process of loading the image, converting it to the appropriate color space, and using the face_recognition library to detect faces with improved accuracy by trying both the CNN and HOG models. The results will be logged for better visibility and debugging purposes. By processing the image in this way, we can provide feedback to the user about the results of face detection and further utilize this information for face recognition or other features in the application.
        if image is not None: # Check if the image was loaded successfully (i.e., if it is not None) before attempting to draw face boxes. If the image is None, it means that there was an issue with loading the image (e.g., due to an incorrect path or unsupported format), and we will skip the step of drawing face boxes to avoid errors. This check ensures that we only attempt to draw face boxes on valid images, improving the robustness of the application and preventing potential crashes or unexpected behavior when processing invalid images.
            draw_face_boxes(image, face_locations) # If the image was loaded successfully, draw boxes around the detected faces using the draw_face_boxes function. This function will loop through each detected face location and draw a rectangle around it in the image. By drawing face boxes, we can visually indicate where faces were detected in the image, providing feedback to the user about the results of the face detection process. This can enhance the user experience by allowing them to see which faces were identified in their captured image and can also be useful for debugging and performance monitoring purposes when testing the application with different types of images.
        
        print(f"{'='*50}\n") # Print a separator line for better visibility in the console output, making it easier to distinguish between different capture events and their corresponding logs. This helps in organizing the console output and improving readability, especially when processing multiple captures or when troubleshooting issues related to image capture and face detection.
        return jsonify({"message": "Image processed successfully.", "results": face_locations}) # Return a JSON response indicating that the image was processed successfully, along with the results of face detection (i.e., the locations of detected faces). This provides feedback to the user about the outcome of their capture and allows them to see the results of the face detection process in a structured format. The JSON response can be easily parsed and displayed in the frontend of the application, enhancing the user experience by providing clear and informative feedback about their captured image and the detected faces within it.
    except Exception as e: # Catch any exceptions that occur during the image capture and processing steps, log the error message, and return a JSON response indicating that an error occurred along with the error message. This allows us to handle unexpected issues gracefully without crashing the application, providing feedback to the user about what went wrong and allowing them to take corrective action if necessary. By implementing error handling, we can improve the robustness and user experience of the face recognition system, ensuring that it can gracefully handle issues such as missing image data, invalid image formats, or other unexpected errors that may arise during image capture and processing.
        print(f" Error processing captured image: {str(e)}") # Print an error message indicating that there was an issue processing the captured image, along with the specific error message. This provides immediate feedback in the console about the error that occurred during the capture and processing steps, helping developers and users understand what went wrong and allowing them to take corrective action if necessary. This message will be displayed in the console or terminal where the application is running, aiding in troubleshooting and debugging efforts related to image capture and face detection.
        logging.exception("Error processing the captured image.") # Log the exception with a message indicating that there was an error processing the captured image. This will include the stack trace and error details in the application logs, which can be useful for troubleshooting and debugging issues related to image capture and face detection. Logging the exception also creates a record of the error for future reference and analysis, especially when investigating cases where users may have trouble capturing images or when testing the application with different types of requests.
        return jsonify({"error": str(e)}), 500 # Return a JSON response indicating that an error occurred during the processing of the captured image, along with the specific error message, and a 500 Internal Server Error status code. This informs the user about the issue that occurred and allows them to take corrective action if necessary. The JSON response provides a structured format for conveying error information, which can be easily parsed and displayed in the frontend of the application for better user experience.

# Function to capture video from DroidCam
def capture_from_droidcam(): # Define a function to capture video from DroidCam, which is a popular app that allows users to use their smartphone camera as a webcam for their computer. This function will attempt to access the video feed from DroidCam and display it in a window. By implementing this function, we can provide an additional way for users to capture images for face recognition using their smartphone cameras, enhancing the versatility and usability of the face recognition system.
    cap = cv2.VideoCapture(droidcam_index) # Attempt to open the video feed from DroidCam using the specified index (e.g., 0, 1, etc.). This will allow us to access the video stream from the smartphone camera that is being used as a webcam through DroidCam. By trying to open the video feed, we can determine if the connection to DroidCam is successful and proceed with capturing video frames for display and potential face recognition processing.

    if not cap.isOpened(): # Check if the video feed from DroidCam was opened successfully. If it was not opened, it means that there is an issue with the connection to DroidCam (e.g., it may not be running, the index may be incorrect, or there may be a problem with the webcam setup). In this case, we will print an error message indicating that we cannot open DroidCam and suggest checking the connection. This provides feedback to the user about the issue and allows them to troubleshoot the connection to ensure that they can use their smartphone camera for capturing images in the face recognition system.
        print("Không thể mở DroidCam. Kiểm tra kết nối.") # Print an error message indicating that we cannot open DroidCam and suggest checking the connection. This provides feedback to the user about the issue with accessing the video feed from DroidCam and allows them to troubleshoot the connection to ensure that they can use their smartphone camera for capturing images in the face recognition system. This message will be displayed in the console or terminal where the application is running, helping developers and users understand what went wrong when trying to access DroidCam.
        return # end the function early if we cannot open the video feed from DroidCam 

    while True: # start an infinite
        ret, frame = cap.read() # Read a frame from the video feed. The ret variable will indicate whether the frame was read successfully, and the frame variable will contain the actual image data of the frame. By reading frames in a loop, we can continuously capture video from DroidCam and display it in real-time, allowing users to see the video feed from their smartphone camera and potentially use it for face recognition processing.
        if not ret: # Check if the frame was read successfully. If ret is False, it means that there was an issue with reading the frame from the video feed (e.g., the connection to DroidCam may have been lost, or there may be a problem with the webcam setup). In this case, we will print an error message indicating that we cannot receive frames from DroidCam and break the loop to stop trying to read frames. This provides feedback to the user about the issue and allows them to troubleshoot the connection to ensure that they can use their smartphone camera for capturing images in the face recognition system.
            print("Không nhận được khung hình từ DroidCam.") # Print an error message indicating that we cannot receive frames from DroidCam. This provides feedback to the user about the issue with reading frames from the video feed and allows them to troubleshoot the connection to ensure that they can use their smartphone camera for capturing images in the face recognition system. This message will be displayed in the console or terminal where the application is running, helping developers and users understand what went wrong when trying to read frames from DroidCam.
            break # end the loop if we cannot read frames from DroidCam

        # Hiển thị khung hình từ DroidCam
        cv2.imshow("DroidCam Feed", frame) # Display the frame from DroidCam in a window titled "DroidCam Feed". This allows users to see the video feed from their smartphone camera in real-time, providing feedback about what the camera is capturing. By displaying the video feed, we can enhance the user experience and allow them to use their smartphone camera for capturing images that can be processed for face recognition in the application.

        # Nhấn 'q' để thoát
        if cv2.waitKey(1) & 0xFF == ord('q'): # Check if the 'q' key is pressed to exit the video feed. This allows users to close the video window and stop capturing video from DroidCam when they are done. By implementing this functionality, we provide a convenient way for users to exit the video feed without having to forcefully close the application, enhancing the user experience and allowing them to control when they want to stop using their smartphone camera for capturing images in the face recognition system.
            break # end the loop if the 'q' key is pressed

    cap.release() # Release the video capture object to free up system resources. This is important to ensure that we properly close the connection to DroidCam and allow other applications to access the webcam if needed. By releasing the video capture object, we can prevent potential issues with resource leaks and ensure that the application behaves responsibly when it comes to managing system resources.
    cv2.destroyAllWindows() # Close all OpenCV windows that were opened during the video feed. This is important to ensure that we properly clean up the user interface and free up system resources when the user exits the video feed. By destroying all windows, we can prevent potential issues with lingering windows and ensure that the application behaves responsibly when it comes to managing system resources and providing a clean user experience.

if __name__ == "__main__": #    Check if the script is being run directly (i.e., not imported as a module) before executing the code to start the Flask app and capture video from DroidCam. This is a common practice in Python to ensure that certain code only runs when the script is executed directly, allowing for better modularity and reusability of code when importing it into other scripts or applications.
    # Run the Flask app
    from threading import Thread # Import the Thread class from the threading module to allow us to run the Flask app in a separate thread. This is necessary because the Flask app will block the main thread when it is running, and we want to be able to capture video from DroidCam simultaneously without being blocked by the Flask app. By using a separate thread for the Flask app, we can ensure that both the web server and the video capture functionality can run concurrently without interfering with each other.

    # Start the Flask app in a separate thread
    flask_thread = Thread(target=lambda: app.run(debug=True, use_reloader=False)) # Create a new thread to run the Flask app with debug mode enabled and the reloader disabled. This allows us to start the Flask app in a separate thread, enabling us to capture video from DroidCam simultaneously without being blocked by the Flask app. By setting debug=True, we can get detailed error messages and automatic reloading during development, while use_reloader=False prevents the Flask app from restarting itself when code changes are detected, which is important when running it in a separate thread to avoid issues with multiple instances of the app running at the same time.
    flask_thread.start() # Start the thread to run the Flask app. This will allow the Flask app to run in the background while we continue with the main thread to capture video from DroidCam. By starting the thread, we can ensure that both the web server and the video capture functionality can operate concurrently, providing a seamless experience for users who want to use both features of the face recognition system at the same time.

    # Start capturing video from DroidCam
    capture_from_droidcam() # Call the function to start capturing video from DroidCam. This will allow us to access the video feed from the smartphone camera and display it in a window, providing feedback to the user about what the camera is capturing. By starting the video capture, we can enhance the user experience and allow them to use their smartphone camera for capturing images that can be processed for face recognition in the application.